# pipeline name
name: pipeline1

# trigger
on:
  push:
    branches:
      - main

# jobs
jobs:
  print-hello:
    runs-on: ubuntu-latest

    steps:
      - name: print welcome message
        run: echo "welcome to git actions"

      - name: print swarupa
        run: echo "welcome to git actions"