#pipelinename
name: pipeline1
on:
    push:
        branches:
            - main:

                jobs:
                     print-hello:
                         runs-on: ubuntu-latest
                    steps:
                        - name: print welcome message 
                          run: echo "welcome to git actions"

                        - name : print swarupa
                          run:  echo "welcome to git actions"
                    

